#!/bin/sh
# 
# from http://errtheblog.com/posts/89-huba-huba
# Link dot files back into place
#
# TODO:
# Make a linked directory, skip it in the linking process
# Use linked directory to add vim-rails, vim-ruby, etc as submodules
# sym link linked parts back into the places they need to go

echo "Updating/initializing submodules"
git submodule init
git submodule update
# for i in `ls -1d linked_modules/*.svn`; do
#   echo "updating $i svn repo"
#   svn up $i
# done

for i in `ls -1`; do 
  DEST="${HOME}/.${i}"
  if [ "$i" != "install" ] && [ "$i" != "linked_modules" ] && [ "$i" != "README" ] && [ ! -L "${DEST}" ]; then
    if [ -f ${DEST} ] || [ -d ${DEST} ]; then
      echo "Moved existing file or dir to ${DEST}.orig"
      mv -f ${DEST} ${DEST}.orig
    fi
    echo "Added link for ${DEST}"
    ln -nfs "${PWD}/${i}" "${DEST}"
  fi
done

# git push on commit
HOOK=.git/hooks/post-commit
#grep 'git push' ${HOOK} >/dev/null 2>&1
#if [ $? ]; then
  echo 'git push' > .git/hooks/post-commit
  chmod 755 .git/hooks/post-commit
  #echo "installed post-commit hook to push after committing"
#fi
